create table if not exists public.revision_linguistica (
    id bigint generated by default as identity primary key,
    tipo_entidad text not null,
    entidad_id bigint not null,
    clasificacion text not null,
    estado text not null default 'pendiente',
    observacion text,
    revisado_por uuid references public.usuario(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint revision_linguistica_tipo_no_vacio check (btrim(tipo_entidad) <> ''),
    constraint revision_linguistica_clasificacion_no_vacia check (btrim(clasificacion) <> ''),
    constraint revision_linguistica_estado_valido check (
        estado in ('pendiente', 'en_revision', 'aprobada', 'rechazada')
    )
);

alter table public.revision_linguistica enable row level security;

revoke all on public.revision_linguistica from public, anon;
grant select, insert, update on public.revision_linguistica to authenticated;
grant usage, select on sequence public.revision_linguistica_id_seq to authenticated;

create policy "superadmin consulta revisiones linguisticas"
on public.revision_linguistica for select to authenticated
using (exists (
    select 1 from public.super_administrador sa
    where sa.usuario_id = (select auth.uid())
));

create policy "superadmin registra revisiones linguisticas"
on public.revision_linguistica for insert to authenticated
with check (
    revisado_por = (select auth.uid())
    and exists (
        select 1 from public.super_administrador sa
        where sa.usuario_id = (select auth.uid())
    )
);

create policy "superadmin actualiza revisiones linguisticas"
on public.revision_linguistica for update to authenticated
using (exists (
    select 1 from public.super_administrador sa
    where sa.usuario_id = (select auth.uid())
))
with check (
    revisado_por = (select auth.uid())
    and exists (
        select 1 from public.super_administrador sa
        where sa.usuario_id = (select auth.uid())
    )
);

create or replace function public.actualizar_revision_linguistica_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

revoke execute on function public.actualizar_revision_linguistica_updated_at()
from public, anon, authenticated;

create trigger revision_linguistica_actualiza_fecha
before update on public.revision_linguistica
for each row execute function public.actualizar_revision_linguistica_updated_at();
